# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.accounting_general_set_next_document_number_request import AccountingGeneralSetNextDocumentNumberRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountingGeneralSetNextDocumentNumberRequest(unittest.TestCase):
    """AccountingGeneralSetNextDocumentNumberRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountingGeneralSetNextDocumentNumberRequest(self):
        """Test AccountingGeneralSetNextDocumentNumberRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.accounting_general_set_next_document_number_request.AccountingGeneralSetNextDocumentNumberRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
