# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import office_guy_api
from office_guy_api.models.core_typed_order import CoreTypedOrder  # noqa: E501
from office_guy_api.rest import ApiException


class TestCoreTypedOrder(unittest.TestCase):
    """CoreTypedOrder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCoreTypedOrder(self):
        """Test CoreTypedOrder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = office_guy_api.models.core_typed_order.CoreTypedOrder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
