# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import office_guy_api
from office_guy_api.api.accounting__income_items_api import AccountingIncomeItemsApi  # noqa: E501
from office_guy_api.rest import ApiException


class TestAccountingIncomeItemsApi(unittest.TestCase):
    """AccountingIncomeItemsApi unit test stubs"""

    def setUp(self):
        self.api = office_guy_api.api.accounting__income_items_api.AccountingIncomeItemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounting_income_items_create(self):
        """Test case for accounting_income_items_create

        Create income item  # noqa: E501
        """
        pass

    def test_accounting_income_items_list_stock(self):
        """Test case for accounting_income_items_list_stock

        List stock  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
