# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import office_guy_api
from office_guy_api.models.accounting_documents_get_details_request import AccountingDocumentsGetDetailsRequest  # noqa: E501
from office_guy_api.rest import ApiException


class TestAccountingDocumentsGetDetailsRequest(unittest.TestCase):
    """AccountingDocumentsGetDetailsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountingDocumentsGetDetailsRequest(self):
        """Test AccountingDocumentsGetDetailsRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = office_guy_api.models.accounting_documents_get_details_request.AccountingDocumentsGetDetailsRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
