# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import office_guy_api
from office_guy_api.models.response_billing_recurring_cancel_response import ResponseBillingRecurringCancelResponse  # noqa: E501
from office_guy_api.rest import ApiException


class TestResponseBillingRecurringCancelResponse(unittest.TestCase):
    """ResponseBillingRecurringCancelResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseBillingRecurringCancelResponse(self):
        """Test ResponseBillingRecurringCancelResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = office_guy_api.models.response_billing_recurring_cancel_response.ResponseBillingRecurringCancelResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
