# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import office_guy_api
from models.crm_data_delete_entity_request import CRMDataDeleteEntityRequest  # noqa: E501
from office_guy_api.rest import ApiException


class TestCRMDataDeleteEntityRequest(unittest.TestCase):
    """CRMDataDeleteEntityRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCRMDataDeleteEntityRequest(self):
        """Test CRMDataDeleteEntityRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = office_guy_api.models.crm_data_delete_entity_request.CRMDataDeleteEntityRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
