# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import office_guy_api
from office_guy_api.models.response_accounting_general_get_exchange_rate_response import ResponseAccountingGeneralGetExchangeRateResponse  # noqa: E501
from office_guy_api.rest import ApiException


class TestResponseAccountingGeneralGetExchangeRateResponse(unittest.TestCase):
    """ResponseAccountingGeneralGetExchangeRateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseAccountingGeneralGetExchangeRateResponse(self):
        """Test ResponseAccountingGeneralGetExchangeRateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = office_guy_api.models.response_accounting_general_get_exchange_rate_response.ResponseAccountingGeneralGetExchangeRateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
