# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.hash_export__export_api import HashExportExportApi  # noqa: E501
from swagger_client.rest import ApiException


class TestHashExportExportApi(unittest.TestCase):
    """HashExportExportApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.hash_export__export_api.HashExportExportApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounting_hash_export_export_send(self):
        """Test case for accounting_hash_export_export_send

        Sends hash export by mail  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
