# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import office_guy_api
from models.all_of_website_companies_create_request_credentials import AllOfWebsiteCompaniesCreateRequestCredentials  # noqa: E501
from office_guy_api.rest import ApiException


class TestAllOfWebsiteCompaniesCreateRequestCredentials(unittest.TestCase):
    """AllOfWebsiteCompaniesCreateRequestCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfWebsiteCompaniesCreateRequestCredentials(self):
        """Test AllOfWebsiteCompaniesCreateRequestCredentials"""
        # FIXME: construct object with mandatory attributes with example values
        # model = office_guy_api.models.all_of_website_companies_create_request_credentials.AllOfWebsiteCompaniesCreateRequestCredentials()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
