# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import office_guy_api
from office_guy_api.api.accounting__customers_api import AccountingCustomersApi  # noqa: E501
from office_guy_api.rest import ApiException


class TestAccountingCustomersApi(unittest.TestCase):
    """AccountingCustomersApi unit test stubs"""

    def setUp(self):
        self.api = office_guy_api.api.accounting__customers_api.AccountingCustomersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_accounting_customers_create(self):
        """Test case for accounting_customers_create

        Create customer  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
