# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.billing_general_open_u_pay_terminal_response import BillingGeneralOpenUPayTerminalResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestBillingGeneralOpenUPayTerminalResponse(unittest.TestCase):
    """BillingGeneralOpenUPayTerminalResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBillingGeneralOpenUPayTerminalResponse(self):
        """Test BillingGeneralOpenUPayTerminalResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.billing_general_open_u_pay_terminal_response.BillingGeneralOpenUPayTerminalResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
