# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import office_guy_api
from models.all_of_accounting_general_set_next_document_number_request_credentials import AllOfAccountingGeneralSetNextDocumentNumberRequestCredentials  # noqa: E501
from office_guy_api.rest import ApiException


class TestAllOfAccountingGeneralSetNextDocumentNumberRequestCredentials(unittest.TestCase):
    """AllOfAccountingGeneralSetNextDocumentNumberRequestCredentials unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllOfAccountingGeneralSetNextDocumentNumberRequestCredentials(self):
        """Test AllOfAccountingGeneralSetNextDocumentNumberRequestCredentials"""
        # FIXME: construct object with mandatory attributes with example values
        # model = office_guy_api.models.all_of_accounting_general_set_next_document_number_request_credentials.AllOfAccountingGeneralSetNextDocumentNumberRequestCredentials()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
