# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import office_guy_api
from api.crm__views_api import CRMViewsApi  # noqa: E501
from office_guy_api.rest import ApiException


class TestCRMViewsApi(unittest.TestCase):
    """CRMViewsApi unit test stubs"""

    def setUp(self):
        self.api = api.crm__views_api.CRMViewsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_c_rm_views_list_views(self):
        """Test case for c_rm_views_list_views

        List views  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
