# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import office_guy_api
from models.body104 import Body104  # noqa: E501
from office_guy_api.rest import ApiException


class TestBody104(unittest.TestCase):
    """Body104 unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testBody104(self):
        """Test Body104"""
        # FIXME: construct object with mandatory attributes with example values
        # model = office_guy_api.models.body104.Body104()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
