# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.response_website_companies_update_response import ResponseWebsiteCompaniesUpdateResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestResponseWebsiteCompaniesUpdateResponse(unittest.TestCase):
    """ResponseWebsiteCompaniesUpdateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseWebsiteCompaniesUpdateResponse(self):
        """Test ResponseWebsiteCompaniesUpdateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.response_website_companies_update_response.ResponseWebsiteCompaniesUpdateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
