# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.website_users_login_redirect_request import WebsiteUsersLoginRedirectRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestWebsiteUsersLoginRedirectRequest(unittest.TestCase):
    """WebsiteUsersLoginRedirectRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testWebsiteUsersLoginRedirectRequest(self):
        """Test WebsiteUsersLoginRedirectRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.website_users_login_redirect_request.WebsiteUsersLoginRedirectRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
