# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import office_guy_api
from models.response_billing_recurring_list_for_customer_response import ResponseBillingRecurringListForCustomerResponse  # noqa: E501
from office_guy_api.rest import ApiException


class TestResponseBillingRecurringListForCustomerResponse(unittest.TestCase):
    """ResponseBillingRecurringListForCustomerResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponseBillingRecurringListForCustomerResponse(self):
        """Test ResponseBillingRecurringListForCustomerResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = office_guy_api.models.response_billing_recurring_list_for_customer_response.ResponseBillingRecurringListForCustomerResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
