# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.accounting_typed_document_payment import AccountingTypedDocumentPayment  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountingTypedDocumentPayment(unittest.TestCase):
    """AccountingTypedDocumentPayment unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountingTypedDocumentPayment(self):
        """Test AccountingTypedDocumentPayment"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.accounting_typed_document_payment.AccountingTypedDocumentPayment()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
