# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.crm_typed_folder import CRMTypedFolder  # noqa: E501
from swagger_client.rest import ApiException


class TestCRMTypedFolder(unittest.TestCase):
    """CRMTypedFolder unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCRMTypedFolder(self):
        """Test CRMTypedFolder"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.crm_typed_folder.CRMTypedFolder()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
