# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.accounting_typed_payment_credit_card import AccountingTypedPaymentCreditCard  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountingTypedPaymentCreditCard(unittest.TestCase):
    """AccountingTypedPaymentCreditCard unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountingTypedPaymentCreditCard(self):
        """Test AccountingTypedPaymentCreditCard"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.accounting_typed_payment_credit_card.AccountingTypedPaymentCreditCard()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
