# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.accounting_hash_export_export_send_response import AccountingHashExportExportSendResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestAccountingHashExportExportSendResponse(unittest.TestCase):
    """AccountingHashExportExportSendResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountingHashExportExportSendResponse(self):
        """Test AccountingHashExportExportSendResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.accounting_hash_export_export_send_response.AccountingHashExportExportSendResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
