# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import office_guy_api
from office_guy_api.models.accounting_typed_payment_bank_transfer import AccountingTypedPaymentBankTransfer  # noqa: E501
from office_guy_api.rest import ApiException


class TestAccountingTypedPaymentBankTransfer(unittest.TestCase):
    """AccountingTypedPaymentBankTransfer unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAccountingTypedPaymentBankTransfer(self):
        """Test AccountingTypedPaymentBankTransfer"""
        # FIXME: construct object with mandatory attributes with example values
        # model = office_guy_api.models.accounting_typed_payment_bank_transfer.AccountingTypedPaymentBankTransfer()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
