# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.triggers_triggers_subscribe_response import TriggersTriggersSubscribeResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestTriggersTriggersSubscribeResponse(unittest.TestCase):
    """TriggersTriggersSubscribeResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTriggersTriggersSubscribeResponse(self):
        """Test TriggersTriggersSubscribeResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.triggers_triggers_subscribe_response.TriggersTriggersSubscribeResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
