# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class AccountingTypedExpenseItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'int',
        'name': 'str',
        'external_identifier': 'str',
        'search_mode': 'str'
    }

    attribute_map = {
        'id': 'ID',
        'name': 'Name',
        'external_identifier': 'ExternalIdentifier',
        'search_mode': 'SearchMode'
    }

    def __init__(self, id=None, name=None, external_identifier=None, search_mode=None):  # noqa: E501
        """AccountingTypedExpenseItem - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._name = None
        self._external_identifier = None
        self._search_mode = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if external_identifier is not None:
            self.external_identifier = external_identifier
        if search_mode is not None:
            self.search_mode = search_mode

    @property
    def id(self):
        """Gets the id of this AccountingTypedExpenseItem.  # noqa: E501

        OfficeGuy identifier  # noqa: E501

        :return: The id of this AccountingTypedExpenseItem.  # noqa: E501
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AccountingTypedExpenseItem.

        OfficeGuy identifier  # noqa: E501

        :param id: The id of this AccountingTypedExpenseItem.  # noqa: E501
        :type: int
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AccountingTypedExpenseItem.  # noqa: E501

        Expense item name  # noqa: E501

        :return: The name of this AccountingTypedExpenseItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AccountingTypedExpenseItem.

        Expense item name  # noqa: E501

        :param name: The name of this AccountingTypedExpenseItem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def external_identifier(self):
        """Gets the external_identifier of this AccountingTypedExpenseItem.  # noqa: E501

        Expense item external identifier  # noqa: E501

        :return: The external_identifier of this AccountingTypedExpenseItem.  # noqa: E501
        :rtype: str
        """
        return self._external_identifier

    @external_identifier.setter
    def external_identifier(self, external_identifier):
        """Sets the external_identifier of this AccountingTypedExpenseItem.

        Expense item external identifier  # noqa: E501

        :param external_identifier: The external_identifier of this AccountingTypedExpenseItem.  # noqa: E501
        :type: str
        """

        self._external_identifier = external_identifier

    @property
    def search_mode(self):
        """Gets the search_mode of this AccountingTypedExpenseItem.  # noqa: E501


        :return: The search_mode of this AccountingTypedExpenseItem.  # noqa: E501
        :rtype: str
        """
        return self._search_mode

    @search_mode.setter
    def search_mode(self, search_mode):
        """Sets the search_mode of this AccountingTypedExpenseItem.


        :param search_mode: The search_mode of this AccountingTypedExpenseItem.  # noqa: E501
        :type: str
        """
        allowed_values = ["Automatic", "None", "ExternalIdentifier", "Name"]  # noqa: E501
        if search_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `search_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(search_mode, allowed_values)
            )

        self._search_mode = search_mode

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountingTypedExpenseItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountingTypedExpenseItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
