# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AccountingGeneralVerifyBankAccountResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'result': 'bool',
        'is_limited_account': 'bool'
    }

    attribute_map = {
        'result': 'Result',
        'is_limited_account': 'IsLimitedAccount'
    }

    def __init__(self, result=None, is_limited_account=None):  # noqa: E501
        """AccountingGeneralVerifyBankAccountResponse - a model defined in Swagger"""  # noqa: E501
        self._result = None
        self._is_limited_account = None
        self.discriminator = None
        if result is not None:
            self.result = result
        if is_limited_account is not None:
            self.is_limited_account = is_limited_account

    @property
    def result(self):
        """Gets the result of this AccountingGeneralVerifyBankAccountResponse.  # noqa: E501

        Result status:  True = Valid bank account  False = Invalid bank account  Null = Unsupported bank  # noqa: E501

        :return: The result of this AccountingGeneralVerifyBankAccountResponse.  # noqa: E501
        :rtype: bool
        """
        return self._result

    @result.setter
    def result(self, result):
        """Sets the result of this AccountingGeneralVerifyBankAccountResponse.

        Result status:  True = Valid bank account  False = Invalid bank account  Null = Unsupported bank  # noqa: E501

        :param result: The result of this AccountingGeneralVerifyBankAccountResponse.  # noqa: E501
        :type: bool
        """

        self._result = result

    @property
    def is_limited_account(self):
        """Gets the is_limited_account of this AccountingGeneralVerifyBankAccountResponse.  # noqa: E501

        Limited bank account status:  True = Bank account is limited  False = Bank account is not limited  Null = Bank account wasn't verified  # noqa: E501

        :return: The is_limited_account of this AccountingGeneralVerifyBankAccountResponse.  # noqa: E501
        :rtype: bool
        """
        return self._is_limited_account

    @is_limited_account.setter
    def is_limited_account(self, is_limited_account):
        """Sets the is_limited_account of this AccountingGeneralVerifyBankAccountResponse.

        Limited bank account status:  True = Bank account is limited  False = Bank account is not limited  Null = Bank account wasn't verified  # noqa: E501

        :param is_limited_account: The is_limited_account of this AccountingGeneralVerifyBankAccountResponse.  # noqa: E501
        :type: bool
        """

        self._is_limited_account = is_limited_account

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountingGeneralVerifyBankAccountResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountingGeneralVerifyBankAccountResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
