# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AllOfResponseBillingPaymentMethodsSetForCustomerResponseData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'customer_id': 'int',
        'payment_method': 'Object'
    }
    if hasattr(BillingPaymentMethodsSetForCustomerResponse, "swagger_types"):
        swagger_types.update(BillingPaymentMethodsSetForCustomerResponse.swagger_types)

    attribute_map = {
        'customer_id': 'CustomerID',
        'payment_method': 'PaymentMethod'
    }
    if hasattr(BillingPaymentMethodsSetForCustomerResponse, "attribute_map"):
        attribute_map.update(BillingPaymentMethodsSetForCustomerResponse.attribute_map)

    def __init__(self, customer_id=None, payment_method=None, *args, **kwargs):  # noqa: E501
        """AllOfResponseBillingPaymentMethodsSetForCustomerResponseData - a model defined in Swagger"""  # noqa: E501
        self._customer_id = None
        self._payment_method = None
        self.discriminator = None
        if customer_id is not None:
            self.customer_id = customer_id
        if payment_method is not None:
            self.payment_method = payment_method
        BillingPaymentMethodsSetForCustomerResponse.__init__(self, *args, **kwargs)

    @property
    def customer_id(self):
        """Gets the customer_id of this AllOfResponseBillingPaymentMethodsSetForCustomerResponseData.  # noqa: E501

        Customer ID  # noqa: E501

        :return: The customer_id of this AllOfResponseBillingPaymentMethodsSetForCustomerResponseData.  # noqa: E501
        :rtype: int
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """Sets the customer_id of this AllOfResponseBillingPaymentMethodsSetForCustomerResponseData.

        Customer ID  # noqa: E501

        :param customer_id: The customer_id of this AllOfResponseBillingPaymentMethodsSetForCustomerResponseData.  # noqa: E501
        :type: int
        """

        self._customer_id = customer_id

    @property
    def payment_method(self):
        """Gets the payment_method of this AllOfResponseBillingPaymentMethodsSetForCustomerResponseData.  # noqa: E501

        Payment method  # noqa: E501

        :return: The payment_method of this AllOfResponseBillingPaymentMethodsSetForCustomerResponseData.  # noqa: E501
        :rtype: Object
        """
        return self._payment_method

    @payment_method.setter
    def payment_method(self, payment_method):
        """Sets the payment_method of this AllOfResponseBillingPaymentMethodsSetForCustomerResponseData.

        Payment method  # noqa: E501

        :param payment_method: The payment_method of this AllOfResponseBillingPaymentMethodsSetForCustomerResponseData.  # noqa: E501
        :type: Object
        """

        self._payment_method = payment_method

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AllOfResponseBillingPaymentMethodsSetForCustomerResponseData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllOfResponseBillingPaymentMethodsSetForCustomerResponseData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
