# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AllOfResponseCRMDataListEntitiesResponseData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entities': 'list[CoreTypedEntity]',
        'has_next_page': 'bool'
    }
    if hasattr(CRMDataListEntitiesResponse, "swagger_types"):
        swagger_types.update(CRMDataListEntitiesResponse.swagger_types)

    attribute_map = {
        'entities': 'Entities',
        'has_next_page': 'HasNextPage'
    }
    if hasattr(CRMDataListEntitiesResponse, "attribute_map"):
        attribute_map.update(CRMDataListEntitiesResponse.attribute_map)

    def __init__(self, entities=None, has_next_page=None, *args, **kwargs):  # noqa: E501
        """AllOfResponseCRMDataListEntitiesResponseData - a model defined in Swagger"""  # noqa: E501
        self._entities = None
        self._has_next_page = None
        self.discriminator = None
        if entities is not None:
            self.entities = entities
        if has_next_page is not None:
            self.has_next_page = has_next_page
        CRMDataListEntitiesResponse.__init__(self, *args, **kwargs)

    @property
    def entities(self):
        """Gets the entities of this AllOfResponseCRMDataListEntitiesResponseData.  # noqa: E501

        Matched entities  # noqa: E501

        :return: The entities of this AllOfResponseCRMDataListEntitiesResponseData.  # noqa: E501
        :rtype: list[CoreTypedEntity]
        """
        return self._entities

    @entities.setter
    def entities(self, entities):
        """Sets the entities of this AllOfResponseCRMDataListEntitiesResponseData.

        Matched entities  # noqa: E501

        :param entities: The entities of this AllOfResponseCRMDataListEntitiesResponseData.  # noqa: E501
        :type: list[CoreTypedEntity]
        """

        self._entities = entities

    @property
    def has_next_page(self):
        """Gets the has_next_page of this AllOfResponseCRMDataListEntitiesResponseData.  # noqa: E501

        Indicator whether the last page has reached  # noqa: E501

        :return: The has_next_page of this AllOfResponseCRMDataListEntitiesResponseData.  # noqa: E501
        :rtype: bool
        """
        return self._has_next_page

    @has_next_page.setter
    def has_next_page(self, has_next_page):
        """Sets the has_next_page of this AllOfResponseCRMDataListEntitiesResponseData.

        Indicator whether the last page has reached  # noqa: E501

        :param has_next_page: The has_next_page of this AllOfResponseCRMDataListEntitiesResponseData.  # noqa: E501
        :type: bool
        """

        self._has_next_page = has_next_page

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AllOfResponseCRMDataListEntitiesResponseData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllOfResponseCRMDataListEntitiesResponseData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
