# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class AllOfAccountingTypedDocumentPaymentDetailsBankTransfer(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bank_number': 'int',
        'branch_number': 'int',
        'account_number': 'str',
        'reference': 'str'
    }
    if hasattr(AccountingTypedPaymentBankTransfer, "swagger_types"):
        swagger_types.update(AccountingTypedPaymentBankTransfer.swagger_types)

    attribute_map = {
        'bank_number': 'BankNumber',
        'branch_number': 'BranchNumber',
        'account_number': 'AccountNumber',
        'reference': 'Reference'
    }
    if hasattr(AccountingTypedPaymentBankTransfer, "attribute_map"):
        attribute_map.update(AccountingTypedPaymentBankTransfer.attribute_map)

    def __init__(self, bank_number=None, branch_number=None, account_number=None, reference=None, *args, **kwargs):  # noqa: E501
        """AllOfAccountingTypedDocumentPaymentDetailsBankTransfer - a model defined in Swagger"""  # noqa: E501
        self._bank_number = None
        self._branch_number = None
        self._account_number = None
        self._reference = None
        self.discriminator = None
        if bank_number is not None:
            self.bank_number = bank_number
        if branch_number is not None:
            self.branch_number = branch_number
        if account_number is not None:
            self.account_number = account_number
        if reference is not None:
            self.reference = reference
        AccountingTypedPaymentBankTransfer.__init__(self, *args, **kwargs)

    @property
    def bank_number(self):
        """Gets the bank_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501

        Israeli bank number<div><i>For instance, 12 indicates Bank Hapoalim.</i></div>  # noqa: E501

        :return: The bank_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501
        :rtype: int
        """
        return self._bank_number

    @bank_number.setter
    def bank_number(self, bank_number):
        """Sets the bank_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.

        Israeli bank number<div><i>For instance, 12 indicates Bank Hapoalim.</i></div>  # noqa: E501

        :param bank_number: The bank_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501
        :type: int
        """

        self._bank_number = bank_number

    @property
    def branch_number(self):
        """Gets the branch_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501

        Israeli bank branch number  # noqa: E501

        :return: The branch_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501
        :rtype: int
        """
        return self._branch_number

    @branch_number.setter
    def branch_number(self, branch_number):
        """Sets the branch_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.

        Israeli bank branch number  # noqa: E501

        :param branch_number: The branch_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501
        :type: int
        """

        self._branch_number = branch_number

    @property
    def account_number(self):
        """Gets the account_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501

        Bank account number  # noqa: E501

        :return: The account_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501
        :rtype: str
        """
        return self._account_number

    @account_number.setter
    def account_number(self, account_number):
        """Sets the account_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.

        Bank account number  # noqa: E501

        :param account_number: The account_number of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501
        :type: str
        """

        self._account_number = account_number

    @property
    def reference(self):
        """Gets the reference of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501

        Bank reference number  # noqa: E501

        :return: The reference of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501
        :rtype: str
        """
        return self._reference

    @reference.setter
    def reference(self, reference):
        """Sets the reference of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.

        Bank reference number  # noqa: E501

        :param reference: The reference of this AllOfAccountingTypedDocumentPaymentDetailsBankTransfer.  # noqa: E501
        :type: str
        """

        self._reference = reference

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AllOfAccountingTypedDocumentPaymentDetailsBankTransfer, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AllOfAccountingTypedDocumentPaymentDetailsBankTransfer):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
