# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class BillingTypedChargeItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'item': 'AccountingTypedIncomeItem',
        'quantity': 'int',
        'unit_price': 'float',
        'currency': 'str',
        'description': 'str'
    }

    attribute_map = {
        'item': 'Item',
        'quantity': 'Quantity',
        'unit_price': 'UnitPrice',
        'currency': 'Currency',
        'description': 'Description'
    }

    def __init__(self, item=None, quantity=None, unit_price=None, currency=None, description=None):  # noqa: E501
        """BillingTypedChargeItem - a model defined in Swagger"""  # noqa: E501

        self._item = None
        self._quantity = None
        self._unit_price = None
        self._currency = None
        self._description = None
        self.discriminator = None

        if item is not None:
            self.item = item
        if quantity is not None:
            self.quantity = quantity
        if unit_price is not None:
            self.unit_price = unit_price
        if currency is not None:
            self.currency = currency
        if description is not None:
            self.description = description

    @property
    def item(self):
        """Gets the item of this BillingTypedChargeItem.  # noqa: E501

        Item  # noqa: E501

        :return: The item of this BillingTypedChargeItem.  # noqa: E501
        :rtype: AccountingTypedIncomeItem
        """
        return self._item

    @item.setter
    def item(self, item):
        """Sets the item of this BillingTypedChargeItem.

        Item  # noqa: E501

        :param item: The item of this BillingTypedChargeItem.  # noqa: E501
        :type: AccountingTypedIncomeItem
        """

        self._item = item

    @property
    def quantity(self):
        """Gets the quantity of this BillingTypedChargeItem.  # noqa: E501

        Quantity<div><i>Defaults to 1</i></div>  # noqa: E501

        :return: The quantity of this BillingTypedChargeItem.  # noqa: E501
        :rtype: int
        """
        return self._quantity

    @quantity.setter
    def quantity(self, quantity):
        """Sets the quantity of this BillingTypedChargeItem.

        Quantity<div><i>Defaults to 1</i></div>  # noqa: E501

        :param quantity: The quantity of this BillingTypedChargeItem.  # noqa: E501
        :type: int
        """

        self._quantity = quantity

    @property
    def unit_price(self):
        """Gets the unit_price of this BillingTypedChargeItem.  # noqa: E501

        Single unit price in payment currency<div><i>Leave empty when using UseItemDetails</i></div>  # noqa: E501

        :return: The unit_price of this BillingTypedChargeItem.  # noqa: E501
        :rtype: float
        """
        return self._unit_price

    @unit_price.setter
    def unit_price(self, unit_price):
        """Sets the unit_price of this BillingTypedChargeItem.

        Single unit price in payment currency<div><i>Leave empty when using UseItemDetails</i></div>  # noqa: E501

        :param unit_price: The unit_price of this BillingTypedChargeItem.  # noqa: E501
        :type: float
        """

        self._unit_price = unit_price

    @property
    def currency(self):
        """Gets the currency of this BillingTypedChargeItem.  # noqa: E501

        Payment currency<div><i>Leave empty for company currency or when using UseItemDetails</i></div>  # noqa: E501

        :return: The currency of this BillingTypedChargeItem.  # noqa: E501
        :rtype: str
        """
        return self._currency

    @currency.setter
    def currency(self, currency):
        """Sets the currency of this BillingTypedChargeItem.

        Payment currency<div><i>Leave empty for company currency or when using UseItemDetails</i></div>  # noqa: E501

        :param currency: The currency of this BillingTypedChargeItem.  # noqa: E501
        :type: str
        """
        allowed_values = ["ILS", "USD", "EUR", "CAD", "CHF", "GBP", "AUD"]  # noqa: E501
        if currency not in allowed_values:
            raise ValueError(
                "Invalid value for `currency` ({0}), must be one of {1}"  # noqa: E501
                .format(currency, allowed_values)
            )

        self._currency = currency

    @property
    def description(self):
        """Gets the description of this BillingTypedChargeItem.  # noqa: E501

        Item description  # noqa: E501

        :return: The description of this BillingTypedChargeItem.  # noqa: E501
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description):
        """Sets the description of this BillingTypedChargeItem.

        Item description  # noqa: E501

        :param description: The description of this BillingTypedChargeItem.  # noqa: E501
        :type: str
        """

        self._description = description

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BillingTypedChargeItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BillingTypedChargeItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
