# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class BillingPaymentsListResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payments': 'list[BillingTypedPayment]',
        'has_next_page': 'bool'
    }

    attribute_map = {
        'payments': 'Payments',
        'has_next_page': 'HasNextPage'
    }

    def __init__(self, payments=None, has_next_page=None):  # noqa: E501
        """BillingPaymentsListResponse - a model defined in Swagger"""  # noqa: E501
        self._payments = None
        self._has_next_page = None
        self.discriminator = None
        if payments is not None:
            self.payments = payments
        if has_next_page is not None:
            self.has_next_page = has_next_page

    @property
    def payments(self):
        """Gets the payments of this BillingPaymentsListResponse.  # noqa: E501


        :return: The payments of this BillingPaymentsListResponse.  # noqa: E501
        :rtype: list[BillingTypedPayment]
        """
        return self._payments

    @payments.setter
    def payments(self, payments):
        """Sets the payments of this BillingPaymentsListResponse.


        :param payments: The payments of this BillingPaymentsListResponse.  # noqa: E501
        :type: list[BillingTypedPayment]
        """

        self._payments = payments

    @property
    def has_next_page(self):
        """Gets the has_next_page of this BillingPaymentsListResponse.  # noqa: E501


        :return: The has_next_page of this BillingPaymentsListResponse.  # noqa: E501
        :rtype: bool
        """
        return self._has_next_page

    @has_next_page.setter
    def has_next_page(self, has_next_page):
        """Sets the has_next_page of this BillingPaymentsListResponse.


        :param has_next_page: The has_next_page of this BillingPaymentsListResponse.  # noqa: E501
        :type: bool
        """

        self._has_next_page = has_next_page

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(BillingPaymentsListResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, BillingPaymentsListResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
