# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body186(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'customer': 'Object',
        'payment_method': 'Object',
        'single_use_token': 'str',
        'credentials': 'Object'
    }
    if hasattr(BillingPaymentMethodsSetForCustomerRequest, "swagger_types"):
        swagger_types.update(BillingPaymentMethodsSetForCustomerRequest.swagger_types)

    attribute_map = {
        'customer': 'Customer',
        'payment_method': 'PaymentMethod',
        'single_use_token': 'SingleUseToken',
        'credentials': 'Credentials'
    }
    if hasattr(BillingPaymentMethodsSetForCustomerRequest, "attribute_map"):
        attribute_map.update(BillingPaymentMethodsSetForCustomerRequest.attribute_map)

    def __init__(self, customer=None, payment_method=None, single_use_token=None, credentials=None, *args, **kwargs):  # noqa: E501
        """Body186 - a model defined in Swagger"""  # noqa: E501
        self._customer = None
        self._payment_method = None
        self._single_use_token = None
        self._credentials = None
        self.discriminator = None
        self.customer = customer
        if payment_method is not None:
            self.payment_method = payment_method
        if single_use_token is not None:
            self.single_use_token = single_use_token
        self.credentials = credentials
        BillingPaymentMethodsSetForCustomerRequest.__init__(self, *args, **kwargs)

    @property
    def customer(self):
        """Gets the customer of this Body186.  # noqa: E501

        Customer details  # noqa: E501

        :return: The customer of this Body186.  # noqa: E501
        :rtype: Object
        """
        return self._customer

    @customer.setter
    def customer(self, customer):
        """Sets the customer of this Body186.

        Customer details  # noqa: E501

        :param customer: The customer of this Body186.  # noqa: E501
        :type: Object
        """
        if customer is None:
            raise ValueError("Invalid value for `customer`, must not be `None`")  # noqa: E501

        self._customer = customer

    @property
    def payment_method(self):
        """Gets the payment_method of this Body186.  # noqa: E501

        Payment method  # noqa: E501

        :return: The payment_method of this Body186.  # noqa: E501
        :rtype: Object
        """
        return self._payment_method

    @payment_method.setter
    def payment_method(self, payment_method):
        """Sets the payment_method of this Body186.

        Payment method  # noqa: E501

        :param payment_method: The payment_method of this Body186.  # noqa: E501
        :type: Object
        """

        self._payment_method = payment_method

    @property
    def single_use_token(self):
        """Gets the single_use_token of this Body186.  # noqa: E501

        Single use token, for all payment details (CardNumber, Expiration, CVV, CitizenID).<div><i>Used primarily by the Payments JavaScript API.</i></div>  # noqa: E501

        :return: The single_use_token of this Body186.  # noqa: E501
        :rtype: str
        """
        return self._single_use_token

    @single_use_token.setter
    def single_use_token(self, single_use_token):
        """Sets the single_use_token of this Body186.

        Single use token, for all payment details (CardNumber, Expiration, CVV, CitizenID).<div><i>Used primarily by the Payments JavaScript API.</i></div>  # noqa: E501

        :param single_use_token: The single_use_token of this Body186.  # noqa: E501
        :type: str
        """

        self._single_use_token = single_use_token

    @property
    def credentials(self):
        """Gets the credentials of this Body186.  # noqa: E501

        Company API credentials  # noqa: E501

        :return: The credentials of this Body186.  # noqa: E501
        :rtype: Object
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials):
        """Sets the credentials of this Body186.

        Company API credentials  # noqa: E501

        :param credentials: The credentials of this Body186.  # noqa: E501
        :type: Object
        """
        if credentials is None:
            raise ValueError("Invalid value for `credentials`, must not be `None`")  # noqa: E501

        self._credentials = credentials

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body186, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body186):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
