# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 2020-06-20
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Body304(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'email_address': 'str',
        'password': 'str',
        'credentials': 'Object'
    }
    if hasattr(WebsiteUsersLoginRedirectRequest, "swagger_types"):
        swagger_types.update(WebsiteUsersLoginRedirectRequest.swagger_types)

    attribute_map = {
        'email_address': 'EmailAddress',
        'password': 'Password',
        'credentials': 'Credentials'
    }
    if hasattr(WebsiteUsersLoginRedirectRequest, "attribute_map"):
        attribute_map.update(WebsiteUsersLoginRedirectRequest.attribute_map)

    def __init__(self, email_address=None, password=None, credentials=None, *args, **kwargs):  # noqa: E501
        """Body304 - a model defined in Swagger"""  # noqa: E501
        self._email_address = None
        self._password = None
        self._credentials = None
        self.discriminator = None
        self.email_address = email_address
        self.password = password
        self.credentials = credentials
        WebsiteUsersLoginRedirectRequest.__init__(self, *args, **kwargs)

    @property
    def email_address(self):
        """Gets the email_address of this Body304.  # noqa: E501

        User email address  # noqa: E501

        :return: The email_address of this Body304.  # noqa: E501
        :rtype: str
        """
        return self._email_address

    @email_address.setter
    def email_address(self, email_address):
        """Sets the email_address of this Body304.

        User email address  # noqa: E501

        :param email_address: The email_address of this Body304.  # noqa: E501
        :type: str
        """
        if email_address is None:
            raise ValueError("Invalid value for `email_address`, must not be `None`")  # noqa: E501

        self._email_address = email_address

    @property
    def password(self):
        """Gets the password of this Body304.  # noqa: E501

        User password  # noqa: E501

        :return: The password of this Body304.  # noqa: E501
        :rtype: str
        """
        return self._password

    @password.setter
    def password(self, password):
        """Sets the password of this Body304.

        User password  # noqa: E501

        :param password: The password of this Body304.  # noqa: E501
        :type: str
        """
        if password is None:
            raise ValueError("Invalid value for `password`, must not be `None`")  # noqa: E501

        self._password = password

    @property
    def credentials(self):
        """Gets the credentials of this Body304.  # noqa: E501

        Company API credentials  # noqa: E501

        :return: The credentials of this Body304.  # noqa: E501
        :rtype: Object
        """
        return self._credentials

    @credentials.setter
    def credentials(self, credentials):
        """Sets the credentials of this Body304.

        Company API credentials  # noqa: E501

        :param credentials: The credentials of this Body304.  # noqa: E501
        :type: Object
        """
        if credentials is None:
            raise ValueError("Invalid value for `credentials`, must not be `None`")  # noqa: E501

        self._credentials = credentials

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Body304, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Body304):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
