# coding: utf-8

"""
    OfficeGuy API

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: v3
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class SMSSMSSendResponse(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'entity_id': 'int',
        'estimated_quota': 'int'
    }

    attribute_map = {
        'entity_id': 'EntityID',
        'estimated_quota': 'EstimatedQuota'
    }

    def __init__(self, entity_id=None, estimated_quota=None):  # noqa: E501
        """SMSSMSSendResponse - a model defined in Swagger"""  # noqa: E501

        self._entity_id = None
        self._estimated_quota = None
        self.discriminator = None

        if entity_id is not None:
            self.entity_id = entity_id
        if estimated_quota is not None:
            self.estimated_quota = estimated_quota

    @property
    def entity_id(self):
        """Gets the entity_id of this SMSSMSSendResponse.  # noqa: E501

        Created SMS entity id  # noqa: E501

        :return: The entity_id of this SMSSMSSendResponse.  # noqa: E501
        :rtype: int
        """
        return self._entity_id

    @entity_id.setter
    def entity_id(self, entity_id):
        """Sets the entity_id of this SMSSMSSendResponse.

        Created SMS entity id  # noqa: E501

        :param entity_id: The entity_id of this SMSSMSSendResponse.  # noqa: E501
        :type: int
        """

        self._entity_id = entity_id

    @property
    def estimated_quota(self):
        """Gets the estimated_quota of this SMSSMSSendResponse.  # noqa: E501

        Estimated quota  # noqa: E501

        :return: The estimated_quota of this SMSSMSSendResponse.  # noqa: E501
        :rtype: int
        """
        return self._estimated_quota

    @estimated_quota.setter
    def estimated_quota(self, estimated_quota):
        """Sets the estimated_quota of this SMSSMSSendResponse.

        Estimated quota  # noqa: E501

        :param estimated_quota: The estimated_quota of this SMSSMSSendResponse.  # noqa: E501
        :type: int
        """

        self._estimated_quota = estimated_quota

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SMSSMSSendResponse, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SMSSMSSendResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
